<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Auth\Middleware\Authenticate as Middleware;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     */
    protected function redirectTo(Request $request): ?string
    {
        return $request->expectsJson() ? null : route('home');
    }

    public function handle($request, Closure $next, ...$guards)
    {
        if(!$request->user())
        {
            return redirect()->back()->with(['error' => Response::HTTP_FORBIDDEN. ': Access is prohibited.']);
        }
        return parent::handle($request, $next, $guards); // TODO: Change the autogenerated stub
    }
}
